version: "3.7"

services:
  app:
    tty: true
    restart: on-failure
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: develop-stage
    environment:
      - USER=app
    env_file:
      - root/envs/.env
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/root/target
    container_name: stock-backtester-app
    ports:
      - 8010:8000
    command: /bin/bash -c "cargo watch -x run"
    networks:
      - default
    depends_on:
      - postgres
  postgres:
    tty: true
    restart: on-failure
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: stock-backtester-postgres
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stock_backtester
  influxdb:
    image: influxdb:1.8.6
    container_name: stock-backtester-influxdb
    ports:
      - 8086:8086
  grafana:
    tty: true
    restart: on-failure
    image: grafana/grafana:8.0.6
    container_name: stock-backtester-grafana
    ports:
      - 8085:3000
    depends_on:
      - influxdb
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.77.6:8085
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  cargo-cache:
  target-cache:
